export const DOCTORS = '[Doctors]';

export const GET_DOCTORS_REQUEST = `${DOCTORS} GET_DOCTORS_REQUEST`;
export const GET_DOCTORS_SUCCESS = `${DOCTORS} GET_DOCTORS_SUCCESS`;
export const GET_DOCTORS_ERROR = `${DOCTORS} GET_DOCTORS_ERROR`;
