export const USERS = '[Users]';

export const GET_ALL_USERS_REQUEST = `${USERS} GET_ALL_USERS`;
export const GET_ALL_USERS_SUCCESS = `${DOCTORS} GET_ALL_USERS_SUCCESS`;

export const UPDATE_USER_REQUEST = `${USERS} UPDATE_USER_REQUEST`;
export const UPDATE_USER_SUCCESS = `${USERS} UPDATE_USER_SUCCESS`;
