export const PATIENTS = '[Patients]';

export const GET_PATIENT_REQUEST = `${PATIENTS} GET_PATIENT_REQUEST`;
export const GET_PATIENT_SUCCESS = `${PATIENTS} GET_PATIENT_SUCCESS`;
export const GET_PATIENT_ERROR = `${PATIENTS} GET_PATIENT_ERROR`;

export const GET_PATIENT_REQUEST_MEDICAL_RECORD_REQUEST = `${PATIENTS} GET_PATIENT_REQUEST_MEDICAL_RECORD_REQUEST`;
export const GET_PATIENT_REQUEST_MEDICAL_RECORD_SUCCESS = `${PATIENTS} GET_PATIENT_REQUEST_MEDICAL_RECORD_SUCCESS`;
export const GET_PATIENT_REQUEST_MEDICAL_RECORD_ERROR = `${PATIENTS} GET_PATIENT_REQUEST_MEDICAL_RECORD_ERROR`;

export const SAVE_MEDICAL_RECORD = `${PATIENTS} SAVE_MEDICAL_RECORD`;
export const SAVE_MEDICAL_RECORD_ERROR = `${PATIENTS} SAVE_MEDICAL_RECORD_ERROR`;

export const UPDATE_PATIENT_MEDICAL_RECORD = `${PATIENTS} UPDATE_PATIENT_MEDICAL_RECORD`;
