export const APPOINTMENTS = '[Appointments]';

export const GET_DOCTOR_APPOINTMENTS_REQUEST = `${APPOINTMENTS} GET_DOCTOR_APPOINTMENTS_REQUEST`;
export const GET_DOCTOR_APPOINTMENTS_SUCCESS = `${APPOINTMENTS} GET_DOCTOR_APPOINTMENTS_SUCCESS`;
export const GET_DOCTOR_APPOINTMENTS_ERROR = `${APPOINTMENTS} GET_DOCTOR_APPOINTMENTS_ERROR`;
