export const PROFILE = '[Profile]';

export const CHANGE_PASSWORD_REQUEST = `${PROFILE} CHANGE_PASSWORD_REQUEST`;
export const CHANGE_PASSWORD_SUCCESS = `${PROFILE} CHANGE_PASSWORD_SUCCESS`;
export const CHANGE_PASSWORD_ERROR = `${PROFILE} CHANGE_PASSWORD_ERROR`;
